apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "grafana-pv" 
spec:
  storageClassName: grafana-db-sc
  capacity:
    storage: "40Gi" 
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain   
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-0b6ec2b90addde8cc"
