apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "influxdb-pv" 
spec:
  storageClassName: influx-db-sc
  capacity:
    storage: "80Gi" 
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain   
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-05c54ed3ec98ef033"

