version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    hostname: grafana
    networks:
      nonitoring:
        aliases:
            - grafana
    volumes:
      - grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    hostname: influxdb
    networks:
      nonitoring:
        aliases:
            - influxdb

    volumes:
      - influxdb-volume:/var/lib/influxdb
  
  chronograf:
    image: 'chronograf:1.4'
    entrypoint: 'chronograf --kapacitor-url=http://kapacitor:9092 --influxdb-url=http://influxdb:8086'
    depends_on: ['influxdb', 'kapacitor']
    ports: ['8888:8888']
    container_name: chronograf
    hostname: chronograf
    networks:
      nonitoring:
        aliases:
            - chronograf
  kapacitor:
    image: 'kapacitor:1.4'
    depends_on: ['influxdb' ]
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_HOSTNAME=kapacitor
    container_name: kapacitor
    hostname: kapacitor
    networks:
      nonitoring:
        aliases:
            - kapacitor

  github.com/afriexUK/afriex-jmeter-testbench:
    image: "kodjo/kodjobaah:github.com/afriexUK/afriex-jmeter-testbench"
    depends_on: ['influxdb', 'kapacitor', 'chronograf' , 'grafana']
    container_name: github.com/afriexUK/afriex-jmeter-testbench
    hostname: github.com/afriexUK/afriex-jmeter-testbench
    networks:
      nonitoring:
        aliases:
            - github.com/afriexUK/afriex-jmeter-testbench

networks:
  nonitoring:
    driver: "bridge"
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true



