export const REPORT_FETCH_TENANTS = 'REPORT_FETCH_TENANTS';
export const RECEIVE_REPORT_TENANTS = 'RECEIVE_REPORT_TENANTS';
export const RECEIVE_LOGS_FOR_SLAVE = 'RECEIVE_LOGS_FOR_SLAVE';
export const FETCH_LOGS_FOR_SLAVE = 'FETCH_LOGS_FOR_SLAVE';

