apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "chronograf-pv" 
spec:
  storageClassName: chronograf-db-sc
  capacity:
    storage: "40Gi" 
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain   
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-0321d357cbbfadb02"

