apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-jmeter
spec:
  storageClassName: grafana-db-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  volumeName: "grafana-pv"
