apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-jmeter
spec:
  storageClassName: influx-db-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  volumeName: "influxdb-pv"
