kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: afriex-admin-controller
subjects:
- kind: ServiceAccount
  name: afriex-control
  namespace: control
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
