apiVersion: v1
kind: Pod
metadata:
  name: admin-controller
  labels:
    control: admin

spec:
  nodeSelector:
    control: admin
  serviceAccountName: afriex-control
  securityContext:
      fsGroup: 1000
  containers:
  - name: control
    image: 625194385885.dkr.ecr.eu-west-3.amazonaws.com/jmeterstresstest/control:latest
    imagePullPolicy: Always
    args: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]
    ports:
    - containerPort: 60000
    securityContext:
      "privileged": true
      runAsUser: 1000
      runAsGroup: 1000