apiVersion: v1
kind: Service
metadata:
  name: admin-controller
  labels:
    control: admin
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: weavescope
      port: 4040
      targetPort: 4040
    - name: admin
      port: 1323
      targetPort: 1323
    - name: report
      port: 80
      targetPort: 80
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    control: admin
  type: LoadBalancer